---
name: Spell Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typos:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check spelling with typos
        uses: crate-ci/typos@b41eb62e9a8096c9ba6636e2365d3f56018a203c # master
        continue-on-error: true
        with:
          files: .
          config: .typos.toml
